import java.util.Scanner;

public class TwentyQuestions
{
    public static void main (String[] args)
    {
        boolean play = true; //boolean tracking if the user wants to play again
        BinaryTree questionTree = new BinaryTree(); //initialized the tree
        baseTree(questionTree); //fills in the basic tree
        while(play) { //loop to continue the game if the user wants to play again and make the tree smarter
            questionTree.ask(); //method to figure out the user object; the bulk of the game
            Scanner sc = new Scanner(System.in); //scanner to see if the user wants to play again
            System.out.println("Play again? I get smarter with successive plays! Enter Yes or No: ");
            if (sc.nextLine().equals("No")) //if they say no, ends the loop
                play = false;
        }
    }
    public static void baseTree(BinaryTree bt) //method to instantiate the basic question tree
    {
        TreeNode q1 = new TreeNode("Is it an animal?"); //makes nodes of each question
        TreeNode q2 = new TreeNode("Can it fly?");
        TreeNode q3 = new TreeNode("Is it a plant?");
        bt.setRoot(q1); //sets the first question as the root
        q1.setYesNode(q2); //sets the next two questions as the yes and no nodes of the first
        q1.setNoNode(q3);
        TreeNode q4 = new TreeNode("Is it a type of bird?"); //cycle continues until the entire tree is created
        TreeNode q5 = new TreeNode("Is it an aquatic animal?");
        q2.setYesNode(q4);
        q2.setNoNode(q5);
        TreeNode q6 = new TreeNode("Is it a vegetable?");
        TreeNode q7 = new TreeNode("Is it an appliance of some kind?");
        q3.setYesNode(q6);
        q3.setNoNode(q7);
        TreeNode q8 = new TreeNode("Is it a bird people eat?");
        TreeNode q9 = new TreeNode("Is it a type of insect?");
        q4.setYesNode(q8);
        q4.setNoNode(q9);
        TreeNode q10 = new TreeNode("Is it a mammal?");
        TreeNode q11 = new TreeNode("Does it live in the jungle?");
        q5.setYesNode(q10);
        q5.setNoNode(q11);
        TreeNode q12 = new TreeNode("Is it green?");
        TreeNode q13 = new TreeNode("Is it a fruit?");
        q6.setYesNode(q12);
        q6.setNoNode(q13);
        TreeNode q14 = new TreeNode("Is it a kitchen appliance?");
        TreeNode q15 = new TreeNode("Is it kitchenware?");
        q7.setYesNode(q14);
        q7.setNoNode(q15);
        TreeNode q16 = new TreeNode("Is it a very commonly-eaten bird?");
        TreeNode q17 = new TreeNode("Can it talk?");
        q8.setYesNode(q16);
        q8.setNoNode(q17);
        TreeNode q18 = new TreeNode("Does it make a loud buzzing noise?");
        TreeNode q19 = new TreeNode("Is it a flying mammal?");
        q9.setYesNode(q18);
        q9.setNoNode(q19);
        TreeNode q20 = new TreeNode("Does it have a blowhole?");
        TreeNode q21 = new TreeNode("Does it have claws?");
        q10.setYesNode(q20);
        q10.setNoNode(q21);
        TreeNode q22 = new TreeNode("Is it a predator?");
        TreeNode q23 = new TreeNode("Does it live in the arctic?");
        q11.setYesNode(q22);
        q11.setNoNode(q23);
        TreeNode q24 = new TreeNode("Is it all leaf?");
        TreeNode q25 = new TreeNode("Is it a root vegetable?");
        q12.setYesNode(q24);
        q12.setNoNode(q25);
        TreeNode q26 = new TreeNode("Is it citrus?");
        TreeNode q27 = new TreeNode("Is it a flower?");
        q13.setYesNode(q26);
        q13.setNoNode(q27);
        TreeNode q28 = new TreeNode("Is it a cooling appliance?");
        TreeNode q29 = new TreeNode("Does Microsoft make your object?");
        q14.setYesNode(q28);
        q14.setNoNode(q29);
        TreeNode q30 = new TreeNode("Is it a utensil?");
        TreeNode q31 = new TreeNode("Is it an article of clothing?");
        q15.setYesNode(q30);
        q15.setNoNode(q31);
        TreeNode q32 = new TreeNode("Is it most popular at Thanksgiving?");
        TreeNode q33 = new TreeNode("Does its name fill in the blank of Duck Duck ____?");
        q16.setYesNode(q32);
        q16.setNoNode(q33);
        TreeNode q34 = new TreeNode("Is it associated with pirates?");
        TreeNode q35 = new TreeNode("Is it a symbol of America?");
        q17.setYesNode(q34);
        q17.setNoNode(q35);
        TreeNode q36 = new TreeNode("Does it collect pollen?");
        TreeNode q37 = new TreeNode("Is it red with black spots?");
        q18.setYesNode(q36);
        q18.setNoNode(q37);
        TreeNode q38 = new TreeNode("Does it typically live in caves?");
        TreeNode q39 = new TreeNode("Does it glide?");
        q19.setYesNode(q38);
        q19.setNoNode(q39);
        TreeNode q40 = new TreeNode("Is it one of the biggest animals?");
        TreeNode q41 = new TreeNode("Does it have blubber?");
        q20.setYesNode(q40);
        q20.setNoNode(q41);
        TreeNode q42 = new TreeNode("Does it have a seafood food chain named after it?");
        TreeNode q43 = new TreeNode("Is it depicted in the movie Jaws?");
        q21.setYesNode(q42);
        q21.setNoNode(q43);
        TreeNode q44 = new TreeNode("Is it the king of the jungle?");
        TreeNode q45 = new TreeNode("Is it a very nimble animal?");
        q22.setYesNode(q44);
        q22.setNoNode(q45);
        TreeNode q46 = new TreeNode("Is it white?");
        TreeNode q47 = new TreeNode("Is it a common pet?");
        q23.setYesNode(q46);
        q23.setNoNode(q47);
        TreeNode q48 = new TreeNode("Is it a staple in a BLT?");
        TreeNode q49 = new TreeNode("Is its shape reminiscent of a tree?");
        q24.setYesNode(q48);
        q24.setNoNode(q49);
        TreeNode q50 = new TreeNode("Is it orange?");
        TreeNode q51 = new TreeNode("Is it typically spicy?");
        q25.setYesNode(q50);
        q25.setNoNode(q51);
        TreeNode q52 = new TreeNode("Is it orange?");
        TreeNode q53 = new TreeNode("Does it keep the doctor away?");
        q26.setYesNode(q52);
        q26.setNoNode(q53);
        TreeNode q54 = new TreeNode("Is it associated with love?");
        TreeNode q55 = new TreeNode("Is it found in the desert?");
        q27.setYesNode(q54);
        q27.setNoNode(q55);
        TreeNode q56 = new TreeNode("Does it freeze your food?");
        TreeNode q57 = new TreeNode("Does it heat food quickly?");
        q28.setYesNode(q56);
        q28.setNoNode(q57);
        TreeNode q58 = new TreeNode("Is it portable?");
        TreeNode q59 = new TreeNode("Does it wash clothes?");
        q29.setYesNode(q58);
        q29.setNoNode(q59);
        TreeNode q60 = new TreeNode("Do you use it to eat cereal?");
        TreeNode q61 = new TreeNode("Do you cook soup in it?");
        q30.setYesNode(q60);
        q30.setNoNode(q61);
        TreeNode q62 = new TreeNode("Does it have legs?");
        TreeNode q63 = new TreeNode("Is it an object typically associated with kids?");
        q31.setYesNode(q62);
        q31.setNoNode(q63);
        TreeNode a1 = new TreeNode("Is it a turkey?");
        TreeNode a2 = new TreeNode("Is it a chicken?");
        q32.setYesNode(a1);
        q32.setNoNode(a2);
        TreeNode a3 = new TreeNode("Is it a goose?");
        TreeNode a4 = new TreeNode("Is it a pheasant?");
        q33.setYesNode(a3);
        q33.setNoNode(a4);
        TreeNode a5 = new TreeNode("Is it a parrot?");
        TreeNode a6 = new TreeNode("Is it a parakeet?");
        q34.setYesNode(a5);
        q34.setNoNode(a6);
        TreeNode a7 = new TreeNode("Is it an eagle?");
        TreeNode a8 = new TreeNode("Is it an owl?");
        q35.setYesNode(a7);
        q35.setNoNode(a8);
        TreeNode a9 = new TreeNode("Is it a bee?");
        TreeNode a10 = new TreeNode("Is it a fly?");
        q36.setYesNode(a9);
        q36.setNoNode(a10);
        TreeNode a11 = new TreeNode("Is it a ladybug?");
        TreeNode a12 = new TreeNode("Is it a beetle?");
        q37.setYesNode(a11);
        q37.setNoNode(a12);
        TreeNode a13 = new TreeNode("Is it a bat?");
        TreeNode a14 = new TreeNode("Is it a flying squirrel?");
        q38.setYesNode(a13);
        q38.setNoNode(a14);
        TreeNode a15 = new TreeNode("Is it a colugo?");
        TreeNode a16 = new TreeNode("Is it a gecko?");
        q39.setYesNode(a15);
        q39.setNoNode(a16);
        TreeNode a17 = new TreeNode("Is it a whale?");
        TreeNode a18 = new TreeNode("Is it a dolphin?");
        q40.setYesNode(a17);
        q40.setNoNode(a18);
        TreeNode a19 = new TreeNode("Is it an seal?");
        TreeNode a20 = new TreeNode("Is it an otter?");
        q41.setYesNode(a19);
        q41.setNoNode(a20);
        TreeNode a21 = new TreeNode("Is it a lobster?");
        TreeNode a22 = new TreeNode("Is it a crab?");
        q42.setYesNode(a21);
        q42.setNoNode(a22);
        TreeNode a23 = new TreeNode("Is it a shark?");
        TreeNode a24 = new TreeNode("Is it a fish?");
        q43.setYesNode(a23);
        q43.setNoNode(a24);
        TreeNode a25 = new TreeNode("Is it a lion?");
        TreeNode a26 = new TreeNode("Is it a tiger?");
        q44.setYesNode(a25);
        q44.setNoNode(a26);
        TreeNode a27 = new TreeNode("Is it a gazelle?");
        TreeNode a28 = new TreeNode("Is it a sloth?");
        q45.setYesNode(a27);
        q45.setNoNode(a28);
        TreeNode a29 = new TreeNode("Is it a polar bear?");
        TreeNode a30 = new TreeNode("Is it a walrus?");
        q46.setYesNode(a29);
        q46.setNoNode(a30);
        TreeNode a31 = new TreeNode("Is it a dog?");
        TreeNode a32 = new TreeNode("Is it a ferret?");
        q47.setYesNode(a31);
        q47.setNoNode(a32);
        TreeNode a33 = new TreeNode("Is it lettuce?");
        TreeNode a34 = new TreeNode("Is it cabbage?");
        q48.setYesNode(a33);
        q48.setNoNode(a34);
        TreeNode a35 = new TreeNode("Is it broccoli?");
        TreeNode a36 = new TreeNode("Is it peas?");
        q49.setYesNode(a35);
        q49.setNoNode(a36);
        TreeNode a37 = new TreeNode("Is it a carrot?");
        TreeNode a38 = new TreeNode("Is it celery?");
        q50.setYesNode(a37);
        q50.setNoNode(a38);
        TreeNode a39 = new TreeNode("Is it a pepper?");
        TreeNode a40 = new TreeNode("Is it a mushroom?");
        q51.setYesNode(a39);
        q51.setNoNode(a40);
        TreeNode a41 = new TreeNode("Is it an orange?");
        TreeNode a42 = new TreeNode("Is it a lemon?");
        q52.setYesNode(a41);
        q52.setNoNode(a42);
        TreeNode a43 = new TreeNode("Is it an apple?");
        TreeNode a44 = new TreeNode("Is it a banana?");
        q53.setYesNode(a43);
        q53.setNoNode(a44);
        TreeNode a45 = new TreeNode("Is it a rose?");
        TreeNode a46 = new TreeNode("Is it a sunflower?");
        q54.setYesNode(a45);
        q54.setNoNode(a46);
        TreeNode a47 = new TreeNode("Is it a cactus?");
        TreeNode a48 = new TreeNode("Is it a venus flytrap?");
        q55.setYesNode(a47);
        q55.setNoNode(a48);
        TreeNode a49 = new TreeNode("Is it a freezer?");
        TreeNode a50 = new TreeNode("Is it a refrigerator?");
        q56.setYesNode(a49);
        q56.setNoNode(a50);
        TreeNode a51 = new TreeNode("Is it a microwave?");
        TreeNode a52 = new TreeNode("Is it an oven?");
        q57.setYesNode(a51);
        q57.setNoNode(a52);
        TreeNode a53 = new TreeNode("Is it a laptop?");
        TreeNode a54 = new TreeNode("Is it a computer?");
        q58.setYesNode(a53);
        q58.setNoNode(a54);
        TreeNode a55 = new TreeNode("Is it a washer?");
        TreeNode a56 = new TreeNode("Is it a dryer?");
        q59.setYesNode(a55);
        q59.setNoNode(a56);
        TreeNode a57 = new TreeNode("Is it a spoon?");
        TreeNode a58 = new TreeNode("Is it a fork?");
        q60.setYesNode(a57);
        q60.setNoNode(a58);
        TreeNode a59 = new TreeNode("Is it a pot?");
        TreeNode a60 = new TreeNode("Is it a pan?");
        q61.setYesNode(a59);
        q61.setNoNode(a60);
        TreeNode a61 = new TreeNode("Is it a pair of pants?");
        TreeNode a62 = new TreeNode("Is it a shirt?");
        q62.setYesNode(a61);
        q62.setNoNode(a62);
        TreeNode a63 = new TreeNode("Is it a teddy bear?");
        TreeNode a64 = new TreeNode("Is it a truck?");
        q63.setYesNode(a63);
        q63.setNoNode(a64);
    }
}
